dotnet clean BlabberApp.sln
Remove-Item –path ./BlabberApp.Console/obj
Remove-Item –path ./BlabberApp.ConsoleTest/obj
Remove-Item –path ./BlabberApp.Client/obj
Remove-Item –path ./BlabberApp.ClientTest/obj
Remove-Item –path ./BlabberApp.DataStore/obj
Remove-Item –path ./BlabberApp.DataStoreTest/obj
Remove-Item –path ./BlabberApp.Domain/obj
Remove-Item –path ./BlabberApp.DomainTest/obj
Remove-Item –path ./BlabberApp.Services/obj
Remove-Item –path ./BlabberApp.ServicesTest/obj
Remove-Item –path ./BlabberApp.WebApi/obj
Remove-Item –path ./BlabberApp.WebApiTest/obj

Remove-Item –path ./BlabberApp.Console/bin
Remove-Item –path ./BlabberApp.ConsoleTest/bin
Remove-Item –path ./BlabberApp.Client/bin
Remove-Item –path ./BlabberApp.ClientTest/bin
Remove-Item –path ./BlabberApp.DataStore/bin
Remove-Item –path ./BlabberApp.DataStoreTest/bin
Remove-Item –path ./BlabberApp.Domain/bin
Remove-Item –path ./BlabberApp.DomainTest/bin
Remove-Item –path ./BlabberApp.Services/bin
Remove-Item –path ./BlabberApp.ServicesTest/bin
Remove-Item –path ./BlabberApp.WebApi/bin
Remove-Item –path ./BlabberApp.WebApiTest/bin
